// thx https://whattodraw.virink.com for data

module.exports = [
    'A pirate robot burying a treasure',
    'A tradesman selling jars with ideas',
    'A sausage grill fail at Lucifer\'s party',
    'A lost toys island',
    'A fireman who fears fire',
    'The Inquisition in the insect world',
    'A Fish army conquering the land',
    'A fiery fruit',
    'A key to all doors',
    'A wizard who knew all the mysteries of the universe',
    'A mouse escaping from a cage',
    'The Pokemon\'s daily life in a pokemon ball',
    'The Monster under the bed/in the closet scared by a kid',
    'A milkfueled Cat-drone fighting for fishery resources',
    'A planetary system with two stars',
    'A door to a parallel universe',
    'A boy who built a fence from books around him',
    'An atheistic church',
    'The crucifixion of Satan',
    'A snail scout',
    'A little dude stealing socks at night',
    'A man who wears clothes inside out',
    'A living bubble gum',
    'An underground whale jumped out of the ground',
    'A chest with an unexpected embarrassing treasure',
    'A great fly master',
    'An elephantopus on a beach',
    'A healer troll',
    'A fat, lazy prince on a skinny horse',
    'A grown-up cartoon character',
    'Fairies bathing in a cup',
    'An ogre princess choosing a fiancé',
    'A tree with unusual fruits',
    'A concert of a forest band',
    'A moth preacher advising to fly to the light',
    'Ents planting trees',
    'A sky railway',
    'A holiday dinner of a zombie family',
    'A door to a magical world',
    'An evil Santa',
    'A fish sheperd floating through the air',
    'A monster women rider',
    'A dreadful monster baby',
    'Living drawings of a young artist',
    'A cupid soldier with the latest weaponry',
    'A small mermaid in an aquarium',
    'A slave woman following her master on all fours',
    'A candy golem',
    'Dorms for superheroes',
    'Mario stuck in a toilet',
    'Bears that robbed a bank and are getting in a burning car',
    'A vending machine selling imagination',
    'Fish in aquariums on an orbital station',
    'A unicorn trying to believe in itself',
    'Freddy Krueger – driver of a funny schoolbus',
    'Godzilla and King-Kong playing soldier chess',
    'A red giant falls in love with a star',
    'A dragon buying a princess from a prince',
    'An exhibit of a robot culture museum',
    'A beauty salon for demons',
    'A fruit-vegetable pet',
    'A view out of another planet window',
    'An irregular cashier',
    'A medieval selfie',
    'Monster cuisine',
    'An elf fashion bow',
    'A vampire fashion bow',
    'A witch fashion bow',
    'The talisman of a time traveler',
    'An ancient Egyptian party',
    'A magic shop window',
    'A ticket to the afterworld',
    'A memorial to a fairy tale creature',
    'An intergalactic ice-cream truck',
    'Insects made from jewels',
    'A nuclear umbrella',
    'A fight between Ninja Turtles',
    'An one-man band',
    'The beginning of electronic life',
    'Sewer mermaids',
    'A sun-watch maker',
    'A magic candy box with a surprise',
    'A mechanical planet',
    'A mirror which shows all truth about you',
    'The pet of a mad scientist',
    'A lantern working on firefly energy',
    'A collector of voodoo dolls',
    'An air lighthouse',
    'A library of forgotten memories',
    'A soul rocking out in the hell',
    'A faceless violinist',
    'A seller of desired death',
    'The Inquisition headquarters in magic world',
    'A caramel monster',
    'A steampunk Mickey Mouse',
    'The old Peter Pan',
    'Gel for the soul',
    'A Christmas tree from the hell',
    'The Thirteenth month',
    'Alien\'s money',
    'A manual of knowledge',
    'Draw boobs!',
    'A well granting fears',
    'A repairman of damaged toys',
    'A girl with lollipops in her hair',
    'The raven King',
    'A vampire\'s bar',
    'A cemetery for paper airplanes',
    'A little monster\'s treasure',
    'A store of lost things',
    'A cosmonaut kept in an Alien zoo',
    'A monster house',
    'A sad robot',
    'Birds\' attack on a kite',
    'A ferret tied with a knot',
    'A girl holding a cloud on a string',
    'A father presents a crown to his daughter',
    'Candy rain',
    'The world\'s dirtiest sock',
    'A fantastic-creatures zoo',
    'A dead prom',
    'A hut built from a robot\'s rust cabin',
    'An Indian riding a war-bison',
    'A wounded doctor doing first aid to a contused solider',
    'A rinsing racoon',
    'A place, where rainbows begin',
    'A Pacman Family',
    'A classroom at shaman\'s school',
    'A warlock\'s fail during the reading of a spell',
    'A man of the Year 3000',
    'A genie woman',
    'A Buddhist monk who doesn\'t respect a statute',
    'A funeral of a vampire',
    'Hugging a cloud',
    'A Book Of Leaves',
    'A prison for ghosts',
    'The artists King',
    'A pestilential doctor',
    'A gloomy genius',
    'A carnivorous rabbit',
    'A little guardian of a forgotten well',
    'The last wizard ever',
    'A seller of exotic animals',
    'The Cat-Behemoth',
    'A saleswoman of ball dresses',
    'A young witcher-hermit',
    'An angel apostate going against Heaven',
    'A girl fighting against a man\'s nightmares',
    'A Vampire\'s baby',
    'A man who tamed a shark',
    'An owl brought a letter from Hogwarts',
    'A vacuum cleaner monster',
    'A dragon who fears princesses',
    'An awkward giant',
    'A fat elf prince',
    'A fluffy robot',
    'A killer fairy',
    'An unlucky wizard',
    'A Mistress of pendulums',
    'A flying doctor',
    'The King of snowflake',
    'A slave rabbit',
    'The granddaughter of an evil wizard',
    'A lonely vampire girl',
    'A chamomile boy',
    'A cunning east-princess',
    'A minstrel-chimneysweep',
    'A mad mermaid',
    'The leader of wizard gnomes',
    'A pretty undead',
    'A good wall monster',
    'A gold maid',
    'A pretty undead',
    'A ballerina orс',
    'A desert archer',
    'A diamond man',
    'A collector of happy memories',
    'A mechanical witch',
    'The prince of a lightless kingdom',
    'The kind grandma of an evil Lord',
    'A satyr anti-social',
    'A centaur in galoshes',
    'A drunk dryad',
    'A sweet-tooth gnome',
    'A fairy living in a teapot',
    'A collector of horseshoes',
    'A fat ghost',
    'A pirate-mutant',
    'A winged golem',
    'A green-fairy hunter',
    'A child solider',
    'A resident of a ceramic city',
    'A gladiator-cosmonaut',
    'A singer hobbit girl',
    'A magic wood carver',
    'A fisherman wizard',
    'The custodian woman of a deserted library',
    'Baby pirates',
    'A monster under the bed',
    'A paper geisha',
    'An octopus clerk',
    'The Goddess of black waters',
    'An evil jedi',
    'Lord Voldemort\'s son',
    'A tooth fairy who steals teeth',
    'A leprechaun who doesn\'t like money',
    'An evil fairy',
    'A man wearing a tutu',
    'A reptile man',
    'A voodoo witch',
    'A girl with unruly hair',
    'A photograph of another reality',
    'The driver of the train to Hell',
    'A snow diva living in a cemetery',
    'A man with split personality',
    'A patchwork creature',
    'Winter spirits making snowflakes',
    'The keeper of a portal to a book world',
    'A blood seller',
    'A treasurer gnome',
    'A pilgrim from the future',
    'The guardian of a key to another worlds',
    'A little monster who likes singing',
    'A collector of children\'s wishes',
    'The king of pillow Kingdome',
    'A star dragon',
    'A skeleton\'s dance',
    'An angel dying in the darkness',
    'The Lord of Darkness',
    'A seller in a Witch Shop',
    'An unlucky chemist',
    'The emotions of a Tomato during a flight',
    'A tree who wants to fly',
    'A monkey with a grenade',
    'A fridge running from a fat girl',
    'The earth after zombie apocalypse',
    'New Year in a volcano crater',
    'Stork and Fox making a selfie',
    'Gods in the modern world',
    'A dance around a palm',
    'Living pencils fighting against an artist',
    'A panda dancing disco',
    'Sleeping beauty and Cinderella fighting over a prince',
    'A gnome and seven Snow Whites',
    'A human invasion to aliens',
    'A world where children rule adults',
    'A firefly seller',
    'An amber raven',
    'A marble harpy',
    'A cat which blends in like chameleon',
    'A phoenix rising from the water',
    'A disco in the underworld',
    'A zombie making selfie with a human',
    'A dancing gipsy',
    'A grandma cooking jam',
    'A tough centaur hopping through a chamomile field',
    'A vegetable fashion show',
    'An old man with musical instruments in his beard',
    'A rastaman-hedgehog',
    'The prince of a chocolate kingdom',
    'A funny undertaker',
    'A journalist shark making a sensation',
    'A sad last unsold donut',
    'The winner of  a laziness competition',
    'The ideologist of a perfectionism movement',
    'A violinist playing for white bears',
    'A mailman delivering kisses',
    'Christmas on Mars',
    'A refrigerator-man',
    'A girl hugging winter dogs',
    'A dream-catcher man',
    'The first giraffe cosmonaut',
    'A Cheburashka Ninja',
    'A tale-teller drinking with his character',
    'A romantic robot who falls in love with a car',
    'A hardcore band of foxes',
    'A sausage for an A-student',
    'A dragonfly cult',
    'The crocodile morality police',
    'God making tea',
    'A wizard on a griffin overtaking a plane',
    'A sky diver hugging a dragon',
    'Tanks riding on broken hearts',
    'Keys to Heaven',
    'Angels playing monopoly',
    'A religion for dinosaurs',
    'Sailors Anonymous',
    'A viking\'s selfie with England on the background',
    'The best friend of a hopeless artist',
    'The recipient of a letter with a soul',
    'Satan has a general cleaning',
    'A shopping mall for snails',
    'A shop with weekends, holydays and vacations',
    'A werewolf cabdriver',
    'A caramel monster',
    'Sharks flying through a stormy sky',
    'A house-spirit on a spaceship',
    'An exhibition of humans\' dreams',
    'Hell for dragons',
    'A predatory bed',
    'A faceless violinist',
    'A library of forgotten memories',
    'An aquarium with a triton',
    'A robot in Ancient Egypt',
    'A lantern working on firefly energy',
    'A herring in a fur coat',
    'A human with a manul-totem',
    'A sea insect',
    'A collector of voodoo dolls',
    'A mechanical planet',
    'Clothes for clouds',
    'An elves\' table game',
    'An electric labyrinth',
    'A lighting system in a deep-sea city',
    'A usual farm of the Sea King',
    'A rider of headless animals',
    'An air lighthouse',
    'A grandma fighting with robbers',
    'A trainer of shadows',
    'A circus of the Jurassic period',
    'The Olimpic gods adapting to a modern reality',
    'A stuffed human in an alien\'s museum',
    'A goblin\'s tribe horoscope',
    'A humanized star sign',
    'A crystal planet',
    'The humanization of planets',
    'The last roman soldier',
    'A flying steam engine',
    'A Bat Queen\'s throne',
    'The death of a pencil',
    'An electrician meeting a Stingray',
    'A sea-horse\'s rider',
    'The heart of a forest',
    'Dwelling space in genie\'s lamp',
    'Winter on a fiery planet',
    'A magic bakery\'s showcase',
    'An Ideas Store',
    'The philosopher\'s stone',
    'An insects orchestra',
    'A night bar inside a pumpkin',
    'A Sky-City landscape',
    'A bird-frog',
    'A village landscape',
    'An office building for artists',
    'An orc marriage to an elf',
    'A house mess',
    'An artists\' war',
    'A bear-zombie',
    'Mountains-castles',
    'Football in outer space',
    'A view from the 144th floor',
    'A rainbow forest',
    'A cosmonaut',
    'A sailing ship',
    'Sea – bath, wind – hairdryer, flowers - hairpin',
    'An octopus playing guitar',
    'A money tree',
    'Our house is an aquarium and we are fishes',
    'A rat-scientist',
    'The aircraft of a new generation',
    'Six gnomes seeing a butterfly for the first time',
    'A conversation between trees',
    'Stars on the ground, forests in the air',
    'A marmalade computer',
    'A space bed',
    'A corn-girl\'s house',
    'A meeting of Egyptian gods',
    'A steampunk Mickey Mouse',
    'A carpet-helicopter',
    'A computer transformed into a man',
    'St.Petersburg as a person',
    'Gel for the soul',
    'A lightbulb got a genius idea',
    'Birthday of the prettiest moth in the world',
    'A hedgehog inside a ball',
    'A rapper-rabbit',
    'A Spartan\'s phone',
    'Alien\'s money',
    'A blanket for clover',
    'A giraffe\'s wedding',
    'Van Gogh painting with photoshop',
    'A tourist in a Underwater kingdom',
    'A manual of knowledge',
    'A floral dragon',
    'An eternal tree\'s seeds',
    'A princess-knight',
    'A hero of our time',
    'A camel in Siberia',
    'A girl with lollipops in her hair',
    'A planet with purple flora',
    'A flooded metropolis',
    'A leviathan guarding the entrance to the Atlantis',
    'Glowing mushrooms in a cave',
    'An altar to an unknown God',
    'A saleswoman of spices',
    'A small pretty creature coming nightly to exchange rubbish for a delicacy',
    'Food flee from a fridge',
    'Small potion jars with tags on wooden shelves',
    'A drunk fairy',
    'A fossil with a small fairy',
    'A living toy on her way to find her adult owner',
    'A cat-centipede',
    'Poseidon walks the Kraken',
    'A well of wishes',
    'An old wood cart filled with flowers',
    'A little prince flying on a falling star',
    'A plantation of stars',
    'The muse of a mad genius',
    'An amulet filled with dark magic',
    'A witch-girl and her black talking parrot',
    'Garden vegetables fighting for territory',
    'Soaring islands',
    'A hare steels carrots at night',
    'A witch fallen into a pond',
    'A luxury house frog',
    'A repairman of damaged toys',
    'Gods from machines',
    'An Emperor sweeping a floor',
    'A hat for stupid questions',
    'A sick ghost',
    'An expelled bookworm',
    'An aristocrat with an unusual cane',
    'A magician in a nightgown',
    'The Spirit of Christmas Holly',
    'A bracelet to rule the elements',
    'A stealer of magic wands',
    'A crystal heart',
    'A living Ragdoll',
    'The Lord of the rain',
    'A dragon-slaying hero girl',
    'An underground traveler',
    'A robot-rogue',
    'The embryo of a computer virus',
    'A humanized graphics tablet',
    'A straitjackets\' designer',
    'A girl cutting light patches',
    'An intergalactic nomad',
    'A cupid hunter',
    'A cabdriver of the future',
    'Alien-monks',
    'A violinist-ropewalker',
    'A polecat-samurai',
    'A chocolate golem',
    'A girl gathering fallen stars',
    'A collector of skulls',
    'A rasta grandma',
    'The Phantom of the Opera',
    'An intelligent mummy',
    'A barman from hell',
    'A collector of heather',
    'A book fairy',
    'The princess of a underwater kingdom',
    'A centaur at the racetrack',
    'A pocket gnome tangling headphones',
    'A hunter in a wolf cape with ears and knives',
    'Hachiko with the ghost of his owner',
    'A ghost in a deserted house',
    'Elves on mushrooms',
    'Cowboy from the future',
    'Souls chained to people',
    'An Interworld traveler standing on a crossroad',
    'A mechanical bear guarding gates',
    'The King of the underbed world',
    'A man observing the end of the world',
    'A giant hugging mountains',
    'A wizard in a modern world',
    'A Living voodoo-doll',
    'A lost toys island',
    'An underwater gardener',
    'A fireman made of straw',
    'A city inside a balloon',
    'A glass frigate',
    'A sky shepherd of cloudy sheep',
    'Old toys against new',
    'An angel with cut wings',
    'A faceless violinist playing not for money',
    'A young caretaker of a huge lost library',
    'An owl reading an old scroll',
    'A nightmare of a deserted hospital',
    'A flower under a glass cover',
    'A collector of dew',
    'A spindrift-girl',
    'A redheaded Elf playing the violin',
    'A lion in gold armor',
    'A girl dreaming to become a knight',
    'The tree of life in the Garden of Eden',
    'A boy with butterfly wings',
    'A dragon from iron rods',
    'A girl with boy\'s habits',
    'A dove in a pot',
    'A postman walking off into the sunset and scattering letters',
    'A Cyclops in sunglasses',
    'The russian King on vocation in Turkey',
    'A dance around a palmtree',
    'A panda dancing Disco',
    'The Virink Universe',
    'Dancing furniture',
    'A candy house',
    'A city under a dome',
    'Bread and tomatoes rain',
    'A train coming out of a television',
    'A corridor in an Art Gallery',
    'The stage of an abandoned theater',
    'A tropical tree growing in a house',
    'The Dogs\' boycott in the square',
    'An Aliens\' fight',
    'Ancient Egyptian God on the computer',
    'A toad on a throne',
    'Cats flying on brooms',
    'Christmas in a robots\' country house',
    'A guitarist on the roof',
    'Ghosts playing hide-and-seek',
    'Spiders stealing a ship in a port',
    'Indian arm wrestling',
    'Gnomes on a Ferris wheel',
    'A spy-dog',
    'The Statue of Liberty overgrown by flowers',
    'An island of discarded toys',
    'The key to your heart',
    'A tree with brilliants',
    'A chamber of Secrets behind a bookcase',
    'Chickens in a Bar',
    'A pocket advisor',
    'A girl with a Chinese lantern',
    'A girl trapping stars with a net',
    'A cave made of huge crystals',
    'A reflection in a broken mirror',
    'An evil genie',
    'A key that opens any door',
    'A girl of glass and a boy of stone',
    'A landscape with Christmas lights',
    'A room with flying candles',
    'A samurai-lady',
    'A man being attacked by his shadow',
    'A dragon in a big city',
    'The superheroes\' cosplay party',
    'A wolf and bobcat playing leapfrog',
    'A city of a forgotten civilization',
    'A white Bear in the tropics',
    'Own inner monsters',
    'A wolf running through the Milky way',
    'The spirit of tea',
    'An age-old book',
    'A Cossack on a horse',
    'Lambs and clouds',
    'A cat that pretends to be an owl',
    'A little dragon opening presents',
    'A landscape around a fairytale castle',
    'An Octopus and a Monkey playing cards',
    'The world inside a glass-ball',
    'A big bear hugging a hare',
    'A squirrel hiding a nut',
    'A creative man\'s room',
    'A forgotten cat in a snowstorm',
    'A sleeping cat and a bunch of mice',
    'A mirror that is a window to a parallel world',
    'A party on a roof',
    'Lambs decorating the Christmas tree',
    'Polecats playing football',
    'A librarian of magic books and artifacts',
    'A little fox showing his tongue',
    'A casino for cavemen',
    'A crocodile - rock star',
    'Walrus-warlord posing for a piece',
    'A cyclops trying on glasses',
    'An alien life-guard on a Martian beach',
    'A worker of a high-tech future',
    'A shy and modest orc',
    'A hare-tyrant',
    'The King of Doughnutland',
    'A squad of battle-owls',
    'A child of an angel and a demon',
    'A fairies\' dwelling-place',
    'A gonzo wizard',
    'A creator of rare artefacts',
    'Tricks of a garden gnome',
    'An evil spirits\' creative evening on a Friday the 13th',
    'A poised brook in a magic forest',
    'The youth of Santa Claus',
    'A coward ghost in an old castle',
    'A voodoo sorcerer after a hard day at work',
    'The exposure of a fake healer',
    'A sand monster been melancholic',
    'Cerberus\' progeny',
    'Horses skipping the clouds',
    'Vanilla mice',
    'An inter-galactic spaghetti delivery bear',
    'A deer jumping on tanks',
    'A hedgehog reading a story to his son',
    'A mole-astronaut',
    'An unlucky little demos',
    'A cat-gladiolus',
    'Sun dust in a Mars aquarium',
    'The population of Venus',
    'A plush monster',
    'The Warmness of a winter valley',
    'An octopus-superstar',
    'A cashier in the spoons\' theater',
    'A spaceship for Infusoria',
    'A mushroom panda',
    'A dinosaur in a pharmacy',
    'A fluffy grampus',
    'A sleeping architect',
    'A mouse on a chandelier',
    'The underbed monster\'s world',
    'A demon who lives in a sugar bowl',
    'An offended muse',
    'An overland ship',
    'A girl wearing a patchwork dress',
    'A star fallen to the ground',
    'Revived Megalomania',
    'Dancing food',
    'A jellyfish race',
    'A cookbook with potions',
    'Live chess',
    'A tree with book pages instead of leaves',
    'Navy in a bubble bath',
    'A fantastic creatures zoo',
    'A Fright\'s bachelorette party',
    'A witch flying on a Hoover',
    'A violinist playing for homeless cats',
    'A builder of castles in the air',
    'A city under a bridge',
    'A mechanic for hearts',
    'A demon of sleeplessness',
    'An aggressive flower in a pot',
    'A candy chimera',
    'A space rose',
    'A robot reading romance histories',
    'A pencil castle',
    'The Boss of the arctic mafia',
    'A space botanical Garden',
    'A flame fish',
    'A city under a blanket',
    'Elves in the subway',
    'A mermaid eating sushi in the bathtub',
    'A smoking apple',
    'A man made of fruits',
    'A Martian landscape',
    'Carlson stuck in a window',
    'A dragonfly trying on a new chaplet',
    'Your own country as an animal',
    'A sandwich forest',
    'An aliens\' school',
    'A snail-professor',
    'Your dream day',
    'You in your dream city',
    'A gloomy dolphin',
    'Cockroaches playing jazz in your head',
    'A vampire on a diet',
    'A cinema during the first 2 min of a movie',
    'A starfish with a star syndrome',
    'A guitar and a violin on a date',
    'What the Sun does when we don\'t see it',
    'An angel throwing a snowflake from a cloud',
    'Your last Valentine\'s Day',
    'A spider living in you room\'s corner witch catches flies and brings them to you at night',
    'The world of myope man',
    'An artist\'s Birthday',
    'The meeting of an eastern horoscope',
    'The demon inside us',
    'A night in Paradise',
    'A zippered mouth',
    'A present for Santa',
    'On the verge of a dream',
    'Faces under masks',
    'Somebody hugging the Heaven',
    'The princess of mountain trolls',
    'A rose covered in road dust',
    'A fork between the past, the present and the future',
    'The Gold Rush',
    'The price for power',
    'Scales for the soul',
    'A temple for a fictional world',
    'A prison for ghosts',
    'A greenhouse for carnivorous plant',
    'An AI\'s system error',
    'A lightning catcher',
    'An artist who has no ideas to draw',
    'A fallen star in a wonder world',
    'The princess of roses',
    'Race without rules',
    'An artist\'s treasure',
    'Magic pollen',
    'A potion from crocodile tears',
    'Sabbath',
    'A crystal dragon',
    'A ghost train',
    'The Lord of Oceans\' throne',
    'An invisible child\'s friend',
    'A forest\'s soul',
    'A Metal centaur',
    'Leprechauns\' treasures',
    'Music of stars',
    'The jungle book',
    'An unexpected furry friend',
    'A snow bear bringing blizzards',
    'A fox-shaman',
    'An old hero',
    'A machine for blowing out gnomes\' beards',
    'An ancient map of a forgotten treasure',
    'A country of horror',
    'A grown fairy tale character',
    'A fire of goodness',
    'A magician of order and anxiety',
    'A cave of candy golems',
    'The Nymph Underworld',
    'A pocket mirror causing portals',
    'The house of a wizard who does everything opposite',
    'The Apollo\'s Chariot',
    'A key as a character\'s soul',
    'A door to the future',
    'A predictor\'s staff',
    'Residents of Atlantis',
    'A dragon honed on the bottom of a lake',
    'An animal made from paints',
    'A castle made of mirrors',
    'An inverted house and its inhabitants',
    'An ancient witch\'s locket',
    'A castle-monster',
    'An elves\' party',
    'A mechanized elf',
    'The castle of a flower wizard',
    'A dance with a mermaid',
    'A kid in a fairy forest',
    'A living sketchbook',
    'The abduction of a soul',
    'The dream of a tail character',
    'When your beloved is invisible',
    'A failed alchemical experiment',
    'A boiler made of bat wings',
    'Attacking dragons',
    'An archer in close combat',
    'A forest of bones',
    'A sled griffin',
    'The middle Ages in a spirit of “Sin City”',
    'The Death on vocation',
    'The king of dwarves',
    'The princess of air elves',
    'An orc-shaman',
    'A spirit of impassable bogs',
    'A phantom of ruins',
    'A warlock of dungeons',
    'poisonous giant spider',
    'Elemental golems',
    'An aquatic man',
    'An old alchemist',
    'A dwarf-hermit',
    'The darkspawn',
    'An elf-trader',
    'The coat-of-arms and flag of the Northern Kingdom',
    'The mermaids queen\'s diadem',
    'A chest with missing things',
    'A deliverer of dreams',
    'A mountain sphinx',
    'A fire salamander',
    'An orc general',
    'The leader of the barbarian tribe',
    'A flying island\'s navigator',
    'An architect of air castles ',
    'hitchhiker between worlds',
    'A Morpheus\'s apprentice',
    'A dream worlds\' cartographer',
    'A door to the sky',
    'A detector of unauthorized magic',
    'A gargoyle-librarian',
    'A zombie-postman',
    'A diamond flower of madness',
    'A coconut dragon',
    'A girl born with sofa\'s magic',
    'Fish mail',
    'An elf in a beautiful garden playing the harp',
    'The world without gravity',
    'A small black-eyed light-eater',
    'A source of inspiration',
    'The diamond staff of the Queen of Shadows',
    'A knight of abandoned hearts',
    'A Christmas dragon',
    'Playing hide-and-seek with a giant',
    'Fruit cheaters',
    'The talisman of a fog\'s keeper',
    'A burning ice sword',
    'A tree for sacrifice',
    'The gates to Paradise',
    'An angel',
    'The Sun princess\' crown',
    'A wonder forest fairy',
    'Fingers-daggers',
    'An ice wizard',
    'An ice dragon',
    'An ice horseshoe of happiness',
    'An ice crystal',
    'An infernal golem',
    'An elf ashamed of his ears',
    'A spirit cloistered in a mirror',
    'A good Lord of darkness',
    'A shield with an internet connection',
    'A werewolf working as an insurance agent',
    'A King\'s page in a magical network',
    'A castle made of leaves',
    'A myth that became reality',
    'A rejected ruler walking the earth',
    'A fairy destroying plants',
    'A sorcerer\'s house',
    'Diamonds rain',
    'A staff which stops the time',
    'Unicorns fights',
    'The Birth of magic',
    'A knight who is friends with a dragon',
    'An unskilled witch who enchanted herself',
    'Orcs\' toys',
    'Humanization of water, earth, fire and air',
    'A girl with a chain ruling a lightning',
    'God creating the butterfly',
    'Elven money',
    'A huge house-orange',
    'Shaman\'s hat and potions',
    'A magician\'s hat',
    'Soldier\'s armor',
    'Druid\'s living armor',
    'A flute calling from the dead',
    'An all elements altar',
    'A firearm bow',
    'A darkness cape',
    'A chest filled with teeth',
    'A pocket teleport',
    'A priestess of the astral world',
    'A tamer of exotic animals',
    'An astrolabe of the underworld',
    'Fire steppe',
    'A potion of madness',
    'A store of magical powers',
    'The temple of the global balance',
    'A marsh mermaid',
    'A library of spells',
    'A birch hunter bow',
    'A staff of the High Priest',
    'An angry dwarf\'s mace',
    'A paladin\'s new sword',
    'A glass dagger',
    'The purple gown of a salamander queen',
    'The scarlet hat of a wolf-hunter-woman',
    'A knight\'s bib',
    'A helmet with peacock feathers',
    'An invisibility cloak',
    'A black cat in a witch\'s house',
    'A teleport machine on a space station',
    'A repair equipment kit',
    'A space monster',
    'A space trucker',
    'A non-round Earth',
    'An exotic fruit',
    'An insect Lord\'s bangle',
    'A sword of the Sun',
    'An assassin from a desert',
    'A dragon of the Black Sea',
    'A resident of a werewolves village',
    'The goddess of justice',
    'An abandoned library',
    'A potion to remove evils',
    'A TRP\'s wood sword',
    'A bullfinch who imagined himself as a sheriff',
    'A forest where poisonous spiders live',
    'An angry lamb in armor',
    'A bear-warrior',
    'A bone-bow of death',
    'An armor for rideable badger',
    'A peacemaker\'s hammer',
    'A tree of hero\'s skills',
    'A machine to improve weapons',
    'The most useless thing on a battle',
    'A musical instrument which can stop the time',
    'A pretty poisonous mushroom-killer',
    'A sacred plant that heals all ailments',
    'The prophet of the Stone People',
    'A candy cannon',
    'The spirit of snow',
    'An additional mechanical arm',
    'An oblivion potion',
    'Shoes for speed-swim with gills and scales',
    'Costumes for a spy-game',
    'The part of the dungeon "Dark light"',
    'A Garden of dreams',
    'A dark mermaid',
    'The anatomy of any exploding character from any game',
    'A predatory giant flower with jaws',
    'A throne in the main audience hall',
    'An arch as a city entrance',
    'A spiked armor',
    'An eyeball',
    'Your own face',
    'Pimples or warts',
    'Fingers and toes',
    'Emotions',
    'lips',
    'A man standing',
    'A jumping man',
    'A woman in a dress',
    '3 different poses of a man playing a guitar',
    'A tired man sitting',
    'Two figures, talking to each other',
    'A man with long curly hair',
    'Tree different figures dancing waltz',
    'A child catching snowflakes',
    'A man greeting people',
    'A man on a snowboard',
    'Scrapes and scratches on the skin',
    'A Beard',
    'A floating man',
    'Different eye shapes and eye forms',
    'A baseball player hitting a ball',
    'People skating',
    'Draw a face of an old man, carefully tracing all the wrinkles',
    'Climbing (at least five different poses)',
    'A basketball player jumping',
    'A girl choosing a dress in front of a mirror',
    'The face of a sneezing person',
    'A gymnast on a trampoline',
    'A girl lying and reading a book',
    'Kids trying to catch soap bubbles',
    'Self-portrait, 3 different views',
    'A lying pose',
    'Looking over somebody\'s shoulder',
    'How emotions change a person\'s face',
    'People and their pets',
    'Children with their parents',
    'Draw a person you think is perfect',
    'A gymnast with a ribbon/hoop/club',
    'The facial muscles',
    'The face of a blind man',
    'Children or adults playing football',
    'A man doing chin-ups',
    'The face of a newborn child',
    'An androgyny\'s portrait',
    'A gymnast-girl',
    'The human skeleton',
    'girl with closed eyes and disheveled hair',
    'A man with a weapon',
    'A running kid',
    'A human under water',
    'A man in a strait jacket',
    'A sleeping human',
    'A human playing guitar',
    'A half-steel man',
    'Pianist\'s fingers',
    'A released prisoner',
    'The legs of a dancer',
    'A kid drawing on the sand',
    'A mother braiding her daughter\'s hair',
    'A father messing up his son\'s hair',
    'An albino',
    'Your self-portrait as the opposite gender',
    'A girl brushing her hair',
    'A pregnant woman',
    'A man at play',
    'A man going upstairs',
    'Sign: silence',
    'Eyes with poofy lashes',
    'A torso with a tattoo',
    'A hand holding a rose',
    'A cut on a finger',
    'A blush on the cheeks',
    'A man and BJD',
    'A group of present-day teenagers',
    'A man in a traditional Japanese Kimono',
    'Four different kinds of nose and teeth',
    'A girl cutting her hair off',
    'Flowers in a head',
    'A tasty woman',
    'Humanized seasons of the year',
    'A weird princess',
    'A secret agent',
    'An engrossed reader',
    'A paper man',
    'Flowers inside a skeleton',
    'Diamond eyes',
    'Pose: a man falling down from a skyscraper',
    'Vampire\'s teeth',
    'Knitted entrails',
    'A cross section of a head',
    'Four pictures: childhood, youth, maturity, old age',
    'Yawning',
    'Printing hands',
    'Trying to touch the tip of the nose with the tongue',
    'Pose: resting a hand on the cheek',
    'An artist\'s face expression while he is painting his dream picture',
    'An artist\'s face expression while he is painting details',
    'The Patty-cake',
    'A boy in a pajama',
    'Pose: a human  in a frenzy',
    'Collar bones',
    'A human, who goes against',
    'A human trying to touch the sky',
    'Pose: Parachute jumping',
    'The hands of a confectioner',
    'Hands that sort seashells',
    'The hip-bones from any view',
    'The back, the head tilted forward and protruding vertebras',
    'Lovers taking a shower',
    'A praying man',
    'A person doing a somersault',
    'A self-portrait in zombie style',
    'Phases of the transformation of a human into a werewolf',
    'A humanized android',
    'Sketches of people in public transport'
];
